## Import the libraries

In [1]:
import numpy as np

## Create the arrays

In [6]:
scalar = np.array(2)
vector = np.array((1,2))
matrice = np.array(((1,2), (3,4)))
tensor = np.array((((1,2), (3,4)), ((5,6), (7,8))))

In [14]:
scalar

array(2)

In [15]:
vector

array([1, 2])

In [16]:
matrice

array([[1, 2],
       [3, 4]])

In [17]:
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Transpose

###  Tranpose operation
* The transpose of a matrix is the mirror image of the matrix across a diagonal line, called the main diagonal, running down and to the right, starting from its upper left corner.

 $$(A^T)_{i,j} = A_{j,i}$$


* In the case of a vector, the tranpose operation will change its orientation. If the vector is a row vector, it will be turned into a column vector.
* For a scalar, the tranpose will be the scalar itself

In [7]:
scalar_t = scalar.T
vector_t = vector.T
matrice_t = matrice.T
tensor_t = tensor.T

In [10]:
scalar_t

array(2)

In [11]:
vector_t

array([1, 2])

In [12]:
matrice_t

array([[1, 3],
       [2, 4]])

In [13]:
tensor_t

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])