## Import the libraries

In [9]:
import numpy as np

## Create two matrices

In [10]:
matrix_a = np.array([[1, 1, 1],
                     [1, 5, 1],
                     [1, 1, 1]])


matrix_b = np.array([[1, 2, 1],
                     [1, 2, 1],
                     [1, 2, 1]])

## Addition

In [11]:
np.add(matrix_a, matrix_b)

array([[2, 3, 2],
       [2, 7, 2],
       [2, 3, 2]])

## Substraction

In [12]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -1,  0],
       [ 0,  3,  0],
       [ 0, -1,  0]])

## Multiplication

In [13]:
np.multiply(matrix_a, matrix_b)

array([[ 1,  2,  1],
       [ 1, 10,  1],
       [ 1,  2,  1]])

## Division

In [14]:
np.divide(matrix_a, matrix_b)

array([[ 1. ,  0.5,  1. ],
       [ 1. ,  2.5,  1. ],
       [ 1. ,  0.5,  1. ]])